config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    namespace :admin do
    get '', to: 'base#index', as: '/'
    resources :users
    resources :charts, only: %i[index]
    resources :categories
    resources :books do
      resources :reviews
    end
  end

  resources :admin, only: %i[index delete]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books do
    resources :reviews
  end
  resources :follows, only: %i[create destroy]
  resources :categories
  root 'books#index'
end

app/models/book.rb
class Book < BaseModel
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_attached_file :book_img, :styles => { :book_index => "300x300>", :book_show => "100x100>" }, default_url: "/images/:style/missing.png",
  					:path => ":rails_root/public/uploadfile/:id/:style/:filename",
  					:url => "/uploadfile/:id/:style/:filename"
  validates_attachment_content_type :book_img, :content_type => /^image\/(png|gif|jpeg)/
  scope :search_category , -> (category_id) { where('category_id like ?' , "%#{category_id}%")}
end

app/controllers/admin/books_controller.rb
# frozen_string_literal: true

class Admin::BooksController < Admin::BaseController
  layout 'admin'
  before_action :set_locale
  before_action :find_book, only: %i[show edit update destroy]

  def index
    @page = (params[:page] || 0).to_i
    @book = current_user.books.build
    @books = Book.order(created_at: :desc).paginate(page: params[:page])
    @books = @books.search_title(params[:term]).where(category_id: params[:category_id]) if params[:category_id].present?
    @books = @books.search_title(params[:term])if params[:term].present?
    @categories = Category.pluck(:name, :id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @users = User.all.order(created_at: :desc)
    @reviews = @book.reviews.page(params[:page]).per(3).order(created_at: :desc)
  end

  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.js
      else
        format.js { render js: @book.errors.full_messages,
                             status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    respond_to do |format|
      if @book.save
        format.js
      else
        format.js { render js: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.reviews.destroy_all
    @book.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :publish_date, :author, :category_id,
                                 :book_img, :description)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  WillPaginate.per_page = 3

  def index
    @page = (params[:page] || 0).to_i
    @books = Book.order(created_at: :desc).paginate(page: params[:page])
    @books = @books.search_title(params[:term]).where(category_id: params[:category_id]).paginate(page: params[:page])  if params[:term].present?
    @categories = Category.pluck(:name, :id)


  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def show
    @users = User.all.order(created_at: :desc)
    @reviews = @book.reviews..order(created_at: :desc).page(params[:page])
    respond_to do |format|
      format.js
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      @categories = Category.all.map { |c| [c.name, c.id] }
      render :edit
    end
    respond_to { |format|
      if @book.update(book_params)
        format.js
      else
        format.js { render json: @book.errors.full_messages,
                             status: :unprocessable_entity }
      end

    }
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    if @book.save
      redirect_to root_path
    else
      @categories = Category.all.map { |c| [c.name, c.id] }
      render :new
    end
  end

  def destroy
    @book.reviews.destroy_all
    @book.destroy
    redirect_to root_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :publish_date, :author, :category_id,
                                 :book_img, :description)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/admin/books/_book.html.erb
<tr id="book<%= book.id %>">
  <td>
    <span class="custom-checkbox">
      <input type="checkbox" name="options[]" value="1">
      <label for="checkbox1"></label>
    </span>
  </td>
  <td>
    <%= image_tag book.book_img.url(:book_index),'data-action': "zoom"%>
  </td>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.category.name%></td>
  <td><%= book.publish_date %></td>
  <td>
    <a href="#editBookModal" class="edit"data-target="#editBookModal_<%= book.id %>" data-toggle="modal"  %><i class="material-icons" data-toggle="tooltip"title="Edit">&#xE254;</i></a>
     <a href="#deleteBookModal_<%= book.id %>" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
  </td>
</tr>

app/views/admin/books/_delete.html.erb
<!-- Delete Modal HTML -->
<div id="deleteBookModal_<%= book.id %>" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Book</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete these Books?</p>
        <p class="text-warning"><small>This action cannot be undone.</small></p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Destroy', [:admin, book], method: :delete,
                    remote: true, class: 'admin_delete',
                    data: {toggle: "modal", dismiss: "modal", target: "#modal"} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/books/_edit.html.erb
<!-- Edit Modal HTML -->
<div id="editBookModal_<%= book.id %>" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Book</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [:admin, book], remote: true, method: :PATCH, class: 'form-control',
                            :html => {:multipart => true} do |f| %>
          <%= select_tag(:category_id, options_for_select(@categories), include_blank: "Select a category", class: "form-control") %></br>
          <%= image_tag book.book_img.url(:book_index), 'data-action': "zoom" %>
          <%= f.file_field :book_img, class: 'form-control' %>
          <%= f.input :title %>
          <%= f.input :publish_date %>
          <%= f.input :author %>
          <%= f.input :description %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.button :submit %>
          </div>
        <% end %>
        </div>
  </div>
</div>

app/views/admin/books/_editbook.html.erb
  <td>
    <span class="custom-checkbox">
      <input type="checkbox" name="options[]" value="1">
      <label for="checkbox1"></label>
    </span>
  </td>
  <td>
    <%= image_tag book.book_img.url(:book_index),'data-action': "zoom"%>
  </td>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.category.name%></td>
  <td><%= book.publish_date %></td>
  <td>
    <a href="#editBookModal_<%= book.id %>" class="edit" data-toggle="modal"  %><i class="material-icons" data-toggle="tooltip"title="Edit">&#xE254;</i></a>
    <a href="#deleteBookModal_<%= book.id %>" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
  </td>

app/views/admin/books/_form.html.erb
<%= form_for(@book, remote: true, :html => { :role => "form" }) do |f| %>
<div id="error_explanation" class="bg-danger text-danger">
</div>
 
<div class="row">
 <div class="col-sm-6">
  <div class="form-group">
    <%= f.label :title, :class => "control-label" %>
    <%= f.text_field :title, :class => "form-control first_input"  %>
  </div>
  <div class="form-group">
    <%= f.label :publish_date, :class => "control-label" %>
    <%= f.text_field :publish_date, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author, :class => "control-label" %>
    <%= f.text_field :author, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "control-label" %>
    <%= f.text_field :description, :class => "form-control" %>
  </div>
</div>

  <div class="form-group">
    <%= f.submit  @book.new_record? ? "Create Create" : "Update book", :class => "btn btn-primary" %>
  </div>
</div>
</div>
<% end %>

app/views/admin/books/_new.html.erb
               <!-- Add Modal HTML -->
                <div id="addBookModal" class="modal fade">
                  <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Add New Book</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">
                          <%= simple_form_for [:admin,@book] , remote: true ,method: :post ,:html => { :multipart => true } do |f| %>
                            <%= select_tag(:category_id, options_for_select(@categories), include_blank: "Select a category", class: "form-control") %></br>
                            <%= f.file_field :book_img %>
                            <%= f.input :title %>
                            <%= f.input :publish_date ,as: :date %>
                            <%= f.input :author %>
                            <%= f.input :description,as: :text %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= f.button :submit %>
                          </div>
                        <% end %>
                    </div>
                  </div>
                </div>

app/views/admin/books/_searchbook.html.erb
    <div class="table-wrapper" id="category-table">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>
                    <span class="custom-checkbox">
                      <input type="checkbox" id="selectAll">
                      <label for="selectAll"></label>
                    </span>
          </th>
          <th>Image</th>
          <th>Name</th>
          <th>Author</th>
          <th>Category</th>
          <th>Publish_date</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody id="books">
        <%= render 'admin/books/new' %>
        <% @books.each do |book| %>
          <tr id="book_<%= book.id %>">
            <td>
                      <span class="custom-checkbox">
                        <input type="checkbox" name="options[]" value="1">
                        <label for="checkbox1"></label>
                      </span>
            </td>
            <td>
              <%= image_tag book.book_img.url(:book_index), 'data-action': "zoom" %>
            </td>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.category.name %></td>
            <td><%= book.publish_date %></td>
            <td>
              <a href="#editBookModal_<%= book.id %>" class="edit" data-target="#editBookModal_<%= book.id %>" data-toggle="modal" %>
                <i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i>
              </a>
              <a href="#deleteBookModal_<%= book.id %>" class="delete" data-toggle="modal">
                <i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i>
              </a>
              <%= render 'admin/books/delete', book: book %>
            </td>

          </tr>
          <%= render 'admin/books/edit', book: book %>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="search-results">
    </div>
    <div class="clearfix">
      <div class="hint-text"> <%= page_entries_info @books %></div>
      <ul class="pagination">
        <div class="digg_pagination">
          <%= will_paginate @books, :container => false %>
        </div>
      </ul>
    </div>

app/views/admin/books/create.js.erb
$("<%= escape_javascript(render @book) %>").appendTo("#books");
$('#addBookModal').modal('toggle');
toastr.success('Book created','Book Create');

app/views/admin/books/destroy.js.erb
$('.admin_delete').bind('ajax:success', function () {
      toastr.error('Book destroyed','Book Destroy')
      $(this).closest('tr').fadeOut();
});

app/views/admin/books/index.html.erb
<div class="container-fluid main-container">
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-3">

            <h2><%= I18n.t("admin.books.manager") %> <b><%= I18n.t("admin.books.book") %></b></h2>
          </div>
          <div class="col-sm-7" style="padding-top:1%">
            <%= form_tag(admin_books_path, method: :get, remote: true) do %>
              <div class="col-md-6" id="adv-search">
                <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search by title", autocomplate: 'off' %>
              </div>
              <div class="col-md-4">
                <div class="button-group" style="padding-left:10%">
                  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-cog"> <%= I18n.t("admin.books.category") %></span>
                    <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @categories.each do |category| %>
                      <li> <%= check_box_tag 'category_id[]', category[1], false, id: category[1], 'autocomplate': 'off' %>
                        <span><%= label_tag category[0] %></span></li>
                    <% end %>
                  </ul>
                </div>
              </div>
              <div class="col-md-2" style="padding-left:3%">
                <%= submit_tag 'Search', class: "btn btn-primary", 'data-backdrop': "" %>
              </div>
              </div>
            <% end %>
            <div class="col-sm-2" style="padding-top:1%">
              <a href="#addBookModal" class="btn btn-success" data-toggle="modal" id="add-book"><i class="material-icons">&#xE147;</i>
                <span><%= I18n.t("admin.books.add-book") %></span></a>
            </div>
            </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-wrapper" id="book-table">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>
                <span class="custom-checkbox">
                  <input type="checkbox" id="selectAll">
                  <label for="selectAll"></label>
                </span>
            </th>
            <th><%= I18n.t("admin.books.image") %></th>
            <th><%= I18n.t("admin.books.name") %></th>
            <th><%= I18n.t("admin.books.author") %></th>
            <th><%= I18n.t("admin.books.category") %></th>
            <th><%= I18n.t("admin.books.publish_date") %></th>
            <th><%= I18n.t("admin.books.action") %></th>
          </tr>
          </thead>
          <tbody id="books">
          <%= render 'admin/books/new' %>
          <% @books.each do |book| %>
            <tr id="book_<%= book.id %>">
              <td>
                  <span class="custom-checkbox">
                    <input type="checkbox" name="options[]" value="1">
                    <label for="checkbox1"></label>
                  </span>
              </td>
              <td>
                <%= image_tag book.book_img.url(:book_index), 'data-action': "zoom" %>
              </td>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td><%= book.category.name %></td>
              <td><%= book.publish_date %></td>
              <td>
                <a href="#editBookModal_<%= book.id %>" class="edit" data-target="#editBookModal_<%= book.id %>" data-toggle="modal" %>
                  <i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i>
                </a>
                <a href="#deleteBookModal_<%= book.id %>" class="delete" data-toggle="modal">
                  <i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i>
                </a>
                <%= render 'admin/books/delete', book: book %>
              </td>
            </tr>
            <%= render 'admin/books/edit', book: book %>
          <% end %>
          </tbody>
        </table>

        <div class="clearfix">
          <div class="hint-text"> <%= page_entries_info @books %></div>
          <ul class="pagination">
            <div class="digg_pagination">
              <%= will_paginate @books, :container => false %>
            </div>
          </ul>
        </div>
      </div>
    </div>
    <div id="book-search-results">
    </div>
  </div>
</div>
</div>
<footer class="pull-left footer">
  <p class="col-md-12">
  <hr class="divider">
  footer
  </p>
</footer>
</div>

app/views/admin/books/index.js.erb
$('#book-table').remove();
$('#book-search-results').html('<%= escape_javascript(render('admin/books/searchbook', books:  @books)) %>');
toastr.success('searched','Search Book')

app/views/admin/books/show.html.erb
  <div class = "col-md-4" >
    <%= image_tag @book.book_img.url(:book_index),'data-action': "zoom"%>
    <h2><%= @book.title %></h2>
    <h3><%= @book.publish_date %></h3>
    <h3><%= @book.author %></h3>
    <h3><%= @book.category %></h3>
  </div>
  <div class="row">
  <div class = "col-md-6" >
    <h3 style="font-size:15px;float: right;"><%= @book.description %></h3>
  </div>
</div>
<div class="row" style="padding-top:2%">
  <div class="col-md-2">
  </div>
  <div class="col-md-10">
    <%= render 'admin/reviews/form' %>
    <h2>Comment</h2>
    <div class="rv" style="min-width:<%= @width %>px">
      <%= render 'admin/reviews/review' %>
      <%= link_to_next_page @reviews, 'Load More', remote: true, id: "load_more_link" %>
    </div>
  </div>
</div>

app/views/admin/books/update.js.erb
$("#book_<%= @book.id %>").html("<%= escape_javascript(render('admin/books/editbook', book:  @book)) %>");
$('#editBookModal_<%= @book.id %>').modal('toggle');
toastr.success('Book updated', 'Book Update')