config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    namespace :admin do
    get '', to: 'base#index', as: '/'
    resources :users
    resources :charts, only: %i[index]
    resources :categories
    resources :books do
      resources :reviews
    end
  end

  resources :admin, only: %i[index delete]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books do
    resources :reviews
  end
  resources :follows, only: %i[create destroy]
  resources :categories
  root 'books#index'
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

class Admin::ReviewsController < Admin::BaseController
  layout 'admin'
  before_action :find_review,:find_book,only: %i[edit create update destroy show]

  def new
    @review = @book.reviews.build
  end

  def index
    @page = (params[:page] || 1).to_i
    @review = Review.new
    @reviews = Review.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
    @reviews.each do |review|
      @user = User.find(review.user_id)
      @book = Book.find(review.book_id)
    end
    @users =  User.pluck(:email, :id)
    @books =  Book.pluck(:title, :id)
  end

  def create
    @review = @book.reviews.build(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    respond_to do |format|
      if @review.save
        format.js
      else
        format.js { render js: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def edit; 
  end

  def update
    redirect_to admin_book_review_path if @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment,:book_id,:user_id)
  end


  def find_user
    @user = User.find(params[:user_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :find_book 
  before_action :find_review, only: %i[edit update destroy show]
  WillPaginate.per_page = 2
  def new
    @review = @book.reviews.build
  end

  def index
    @page = (params[:page] || 1).to_i
    @reviews = @book.reviews.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
  end

  def create
    @review = @book.reviews.build(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    redirect_to book_path(@book) if @review.save
  end

  def show; end

  def edit; end

  def update
    redirect_to book_path(@book) if @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= simple_form_for([:admin, @book, @book.reviews.build]) do |f| %>
  <div id="admin-rating-form">
    <label> Rating </label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>
<script>
    $('#admin-rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
    $('#admin-rating-form').raty('reload');
</script>

app/views/admin/reviews/_review.html.erb
  <% if !@reviews.nil? && @reviews.size > 0 %>
    <% @reviews.each do |review| %>
      <p><%= review.user.email %></p>
      <div class="admin-review-rating" data-score="<%= review.rating %>"></div>
      <p> Comment : <%= review.comment %></p>
      <% if current_user.email == review.user.email  %>
        <%= link_to "Edit Review" , edit_admin_book_review_path(@book,review.id) %>
        <%= link_to "Delete" , admin_book_review_path(review.book_id, review ) , method: :delete , :onclick=> "return confirm('Are you sure you want to delete this item?')"  %>
      <% end %>
    <% end %>
  <% end %>
  <script>
    $('.admin-review-rating').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
    $('.admin-review-rating').raty('reload');
  </script>

app/views/admin/reviews/edit.html.erb
<div>
<div class="col-md-2">
</div>
<div class="col-md-10">
<h1>Edit Review</h1>
<%= simple_form_for [@book, @review] do |f | %>
  <div id="admin-rating-form" data-score="<%= @review.rating %>" >
    <label> Rating </label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit , label:"Edit"%>
  <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
<% end %>
</div>
</div>
<script>
  $('#admin-rating-form').raty({
      path: '/assets/',
      scoreName: 'review[rating]'
  });
  $('#admin-rating-form').raty('reload');
</script>

app/views/admin/reviews/index.html.erb
<div class="container-fluid main-container">
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-3">
            <h2>Manage <b>Review</b></h2>
          </div>
          <div class="col-sm-7" style= "padding-top:1%">
            <%= form_tag(admin_reviews_path, method: :get) do  %>
              <div class="col-md-6" id="adv-search">
                <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search by title",autocomplete: 'off' %>
              </div>
              <div class="col-md-2" style = "padding-left:3%">
                <%= submit_tag 'Search', class: "btn btn-primary"  %>
              </div>
            </div>
          <% end %>
          <div class="col-sm-2"style= "padding-top:1%">
            <a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Review</span></a>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-wrapper">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>
                <span class="custom-checkbox">
                  <input type="checkbox" id="selectAll">
                  <label for="selectAll"></label>
                </span>
              </th>
              <th>Rating</th>
              <th>Comment</th>
              <th>User</th>
              <th>Book</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review|  %>
              <tr>
                <td>
                  <span class="custom-checkbox">
                    <input type="checkbox" id="checkbox1" name="options[]" value="1">
                    <label for="checkbox1"></label>
                  </span>
                </td>
                <td><%= review.rating %></td>
                  <td><%= review.comment %></td>
                     <td><%= @user.email %></td>
                      <td><%= @book.title %></td>
                <td>
                  <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                  <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                </td>
              </tr>
              <tr>
                <td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="clearfix">
            <div class="hint-text"> <%= page_entries_info @reviews %></div>
            <ul class="pagination">
              <div class="digg_pagination">
                <%= will_paginate @reviews, :container => false %>
              </div>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="pull-left footer">
  <p class="col-md-12">
    <hr class="divider">
    footer
  </p>
</footer>
</div>
 <div id="addEmployeeModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Add Review</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [:admin ,@review],method: :post, :html => { :multipart => true }  do |f| %>
            <%= f.input :rating %>
             <%= f.input :comment %>
              <%= f.select :book_id, @books %>
              <%= f.select :user_id, @users %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.button :submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>