config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    namespace :admin do
    get '', to: 'base#index', as: '/'
    resources :users
    resources :charts, only: %i[index]
    resources :categories
    resources :books do
      resources :reviews
    end
  end

  resources :admin, only: %i[index delete]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books do
    resources :reviews
  end
  resources :follows, only: %i[create destroy]
  resources :categories
  root 'books#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < BaseModel
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :reviews
  has_many :active_follows, class_name: 'Follow',
                            foreign_key: 'follower_id',
                            dependent: :destroy
  has_many :passive_follows, class_name: 'Follow',
                            foreign_key: 'followed_id',
                            dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower
  # Follows a user.
  def follow(other_user)
    active_follows.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::BaseController
  layout 'admin'
  before_action :authenticate_user!, except: [:index]
  before_action :find_user, only: %i[show edit]

  def index
    @admin = Admin.new
    @admins = Admin.paginate(page: params[:page], per_page: 3).order(created_at: :desc)
    @user = User.new
    @users = User.paginate(page: params[:page], per_page: 3).order(created_at: :desc)
    if params[:term].present?
      @users = @users.search_by_email(params[:term]).paginate(page: params[:page], per_page: 6)
    end
    @current_user = User.find_by_id(session[:current_user_id])
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.js
      else
        format.js { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit;
  end

  def show;
  end

  def update
    redirect_to book_path(@book) if @review.update(review_params)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_user, only: %i[show edit]

  def new
    @user = User.new
  end

  def index
    @users = User.all.order(created_at: :desc) 
    @current_user = User.find_by_id(session[:current_user_id])
  end

  def edit; end

  def show; end

  def update
    redirect_to book_path(@book) if @review.update(review_params)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/admin/users/_new.html.erb
<!-- Add Modal HTML -->
<div id="addUserModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add New Book</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [:admin, @user], remote: true, method: :post, :html => {:multipart => true} do |f| %>
          <%= f.input :email %>
          <%= f.input :password_field, as: :password %>
          <%= f.check_box :admin , class: "form-group"  %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.button :submit %>
          </div>
        <% end %>
        </div>
  </div>
</div>

app/views/admin/users/_user.html.erb
  <tr>
    <td>
                  <span class="custom-checkbox">
                    <input type="checkbox" id="checkbox1" name="options[]" value="1">
                    <label for="checkbox1"></label>
                  </span>
    </td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    <td>
      <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
      <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
    </td>
  </tr>
  <tr>
    <td>
  </tr>

app/views/admin/users/create.js.erb
$("<%= escape_javascript(render @user) %>").appendTo("#users");

app/views/admin/users/index.html.erb
<div class="container-fluid main-container">
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-3">
            <h2>Manage <b>User</b></h2>
          </div>
          <div class="col-sm-7" style="padding-top:1%">
            <%= form_tag(admin_users_path, method: :get) do %>
              <div class="col-md-6" id="adv-search">
                <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search by title", autocomplate: 'off' %>
              </div>
              <div class="col-md-2" style="padding-left:3%">
                <%= submit_tag 'Search', class: "btn btn-primary" %>
              </div>
              </div>
            <% end %>
            <div class="col-sm-2" style="padding-top:1%">
              <a href="#addUserModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i>
                <span>Add New Employee</span></a>
            </div>
            </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-wrapper" id="user-table">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>
                <span class="custom-checkbox">
                  <input type="checkbox" id="selectAll">
                  <label for="selectAll"></label>
                </span>
            </th>
            <th>Email</th>
            <th>Admin</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody id="users">
          <%= render 'admin/users/new' %>
          <% @users.each do |user| %>
            <tr>
              <td>
                  <span class="custom-checkbox">
                    <input type="checkbox" id="checkbox1" name="options[]" value="1">
                    <label for="checkbox1"></label>
                  </span>
              </td>
              <td><%= user.email %></td>
              <td><%= user.password %></td>
              <td><%= user.admin %></td>
              <td>
                <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
              </td>
            </tr>
            <tr>
              <td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="clearfix">
          <div class="hint-text"> <%= page_entries_info @users %></div>
          <ul class="pagination">
            <div class="digg_pagination">
              <%= will_paginate @users, :container => false %>
            </div>
          </ul>
        </div>
      </div>
    </div>
    <div id="user-search-results">

    </div>
  </div>
</div>
</div>
<footer class="pull-left footer">
  <p class="col-md-12">
  <hr class="divider">
  footer
  </p>
</footer>
</div>